//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.UIProcess.wsCxC {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCxC.wsCxCSoap")]
    public interface wsCxCSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBoSPrecio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerBoSPrecio(int IdAuxiliar, int IdBienOServicio, int Periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerBoSPrecio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerBoSPrecioAsync(int IdAuxiliar, int IdBienOServicio, int Periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCxC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertarCxC(int IdAuxiliar, int IdBoS, int IdSocio, int CantDiasNaturalesExpira, decimal Monto, float Cantidad, string TipoMov, string IdLlaveExterna, string Descripcion, int idCuentaAnterior, string UsrCreacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCxC", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertarCxCAsync(int IdAuxiliar, int IdBoS, int IdSocio, int CantDiasNaturalesExpira, decimal Monto, float Cantidad, string TipoMov, string IdLlaveExterna, string Descripcion, int idCuentaAnterior, string UsrCreacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfectarMontoCxC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int AfectarMontoCxC(int IdCuenta, int IdAuxiliar, decimal Monto, float Cantidad, string TipoMov, string Descripcion, string NumDocto, string UsrModif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AfectarMontoCxC", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AfectarMontoCxCAsync(int IdCuenta, int IdAuxiliar, decimal Monto, float Cantidad, string TipoMov, string Descripcion, string NumDocto, string UsrModif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCxC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerCxC(int IdCuenta, int IdAuxiliar, int IdBoS, int IdSocio, int IdEstado, string EstCobro, string IdLlaveExterna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerCxC", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCxCAsync(int IdCuenta, int IdAuxiliar, int IdBoS, int IdSocio, int IdEstado, string EstCobro, string IdLlaveExterna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposdeDeudor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerTiposdeDeudor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposdeDeudor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTiposdeDeudorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposDeIdentificaciones", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerTiposDeIdentificaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposDeIdentificaciones", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTiposDeIdentificacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposDeSocio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ObtenerTiposDeSocio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerTiposDeSocio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTiposDeSocioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarSocio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int RegistrarSocio(string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrCreacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarSocio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RegistrarSocioAsync(string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrCreacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarSocio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ModificarSocio(int IdSocio, string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrModifacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarSocio", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ModificarSocioAsync(int IdSocio, string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrModifacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarSocio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet BuscarSocio(int IdSocio, string Identificacion1, int idTipoIdentif, string Identificacion2, string NombreCompleto, int TipoSocio, string Email, string TelCelular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarSocio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> BuscarSocioAsync(int IdSocio, string Identificacion1, int idTipoIdentif, string Identificacion2, string NombreCompleto, int TipoSocio, string Email, string TelCelular);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsCxCSoapChannel : CxC.UIProcess.wsCxC.wsCxCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsCxCSoapClient : System.ServiceModel.ClientBase<CxC.UIProcess.wsCxC.wsCxCSoap>, CxC.UIProcess.wsCxC.wsCxCSoap {
        
        public wsCxCSoapClient() {
        }
        
        public wsCxCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsCxCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCxCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsCxCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ObtenerBoSPrecio(int IdAuxiliar, int IdBienOServicio, int Periodo) {
            return base.Channel.ObtenerBoSPrecio(IdAuxiliar, IdBienOServicio, Periodo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerBoSPrecioAsync(int IdAuxiliar, int IdBienOServicio, int Periodo) {
            return base.Channel.ObtenerBoSPrecioAsync(IdAuxiliar, IdBienOServicio, Periodo);
        }
        
        public int InsertarCxC(int IdAuxiliar, int IdBoS, int IdSocio, int CantDiasNaturalesExpira, decimal Monto, float Cantidad, string TipoMov, string IdLlaveExterna, string Descripcion, int idCuentaAnterior, string UsrCreacion) {
            return base.Channel.InsertarCxC(IdAuxiliar, IdBoS, IdSocio, CantDiasNaturalesExpira, Monto, Cantidad, TipoMov, IdLlaveExterna, Descripcion, idCuentaAnterior, UsrCreacion);
        }
        
        public System.Threading.Tasks.Task<int> InsertarCxCAsync(int IdAuxiliar, int IdBoS, int IdSocio, int CantDiasNaturalesExpira, decimal Monto, float Cantidad, string TipoMov, string IdLlaveExterna, string Descripcion, int idCuentaAnterior, string UsrCreacion) {
            return base.Channel.InsertarCxCAsync(IdAuxiliar, IdBoS, IdSocio, CantDiasNaturalesExpira, Monto, Cantidad, TipoMov, IdLlaveExterna, Descripcion, idCuentaAnterior, UsrCreacion);
        }
        
        public int AfectarMontoCxC(int IdCuenta, int IdAuxiliar, decimal Monto, float Cantidad, string TipoMov, string Descripcion, string NumDocto, string UsrModif) {
            return base.Channel.AfectarMontoCxC(IdCuenta, IdAuxiliar, Monto, Cantidad, TipoMov, Descripcion, NumDocto, UsrModif);
        }
        
        public System.Threading.Tasks.Task<int> AfectarMontoCxCAsync(int IdCuenta, int IdAuxiliar, decimal Monto, float Cantidad, string TipoMov, string Descripcion, string NumDocto, string UsrModif) {
            return base.Channel.AfectarMontoCxCAsync(IdCuenta, IdAuxiliar, Monto, Cantidad, TipoMov, Descripcion, NumDocto, UsrModif);
        }
        
        public System.Data.DataSet ObtenerCxC(int IdCuenta, int IdAuxiliar, int IdBoS, int IdSocio, int IdEstado, string EstCobro, string IdLlaveExterna) {
            return base.Channel.ObtenerCxC(IdCuenta, IdAuxiliar, IdBoS, IdSocio, IdEstado, EstCobro, IdLlaveExterna);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerCxCAsync(int IdCuenta, int IdAuxiliar, int IdBoS, int IdSocio, int IdEstado, string EstCobro, string IdLlaveExterna) {
            return base.Channel.ObtenerCxCAsync(IdCuenta, IdAuxiliar, IdBoS, IdSocio, IdEstado, EstCobro, IdLlaveExterna);
        }
        
        public System.Data.DataSet ObtenerTiposdeDeudor() {
            return base.Channel.ObtenerTiposdeDeudor();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTiposdeDeudorAsync() {
            return base.Channel.ObtenerTiposdeDeudorAsync();
        }
        
        public System.Data.DataSet ObtenerTiposDeIdentificaciones() {
            return base.Channel.ObtenerTiposDeIdentificaciones();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTiposDeIdentificacionesAsync() {
            return base.Channel.ObtenerTiposDeIdentificacionesAsync();
        }
        
        public System.Data.DataSet ObtenerTiposDeSocio() {
            return base.Channel.ObtenerTiposDeSocio();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ObtenerTiposDeSocioAsync() {
            return base.Channel.ObtenerTiposDeSocioAsync();
        }
        
        public int RegistrarSocio(string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrCreacion) {
            return base.Channel.RegistrarSocio(Identificacion1, IdTipoIdentif1, Identificacion2, NombreCompleto, NombreSocio2, TipoSocio, Email, TelCelular, telefono2, info1, info2, UsrCreacion);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarSocioAsync(string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrCreacion) {
            return base.Channel.RegistrarSocioAsync(Identificacion1, IdTipoIdentif1, Identificacion2, NombreCompleto, NombreSocio2, TipoSocio, Email, TelCelular, telefono2, info1, info2, UsrCreacion);
        }
        
        public int ModificarSocio(int IdSocio, string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrModifacion) {
            return base.Channel.ModificarSocio(IdSocio, Identificacion1, IdTipoIdentif1, Identificacion2, NombreCompleto, NombreSocio2, TipoSocio, Email, TelCelular, telefono2, info1, info2, UsrModifacion);
        }
        
        public System.Threading.Tasks.Task<int> ModificarSocioAsync(int IdSocio, string Identificacion1, int IdTipoIdentif1, string Identificacion2, string NombreCompleto, string NombreSocio2, int TipoSocio, string Email, string TelCelular, string telefono2, string info1, string info2, string UsrModifacion) {
            return base.Channel.ModificarSocioAsync(IdSocio, Identificacion1, IdTipoIdentif1, Identificacion2, NombreCompleto, NombreSocio2, TipoSocio, Email, TelCelular, telefono2, info1, info2, UsrModifacion);
        }
        
        public System.Data.DataSet BuscarSocio(int IdSocio, string Identificacion1, int idTipoIdentif, string Identificacion2, string NombreCompleto, int TipoSocio, string Email, string TelCelular) {
            return base.Channel.BuscarSocio(IdSocio, Identificacion1, idTipoIdentif, Identificacion2, NombreCompleto, TipoSocio, Email, TelCelular);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> BuscarSocioAsync(int IdSocio, string Identificacion1, int idTipoIdentif, string Identificacion2, string NombreCompleto, int TipoSocio, string Email, string TelCelular) {
            return base.Channel.BuscarSocioAsync(IdSocio, Identificacion1, idTipoIdentif, Identificacion2, NombreCompleto, TipoSocio, Email, TelCelular);
        }
    }
}
