//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Utilitarios.Mensajes {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CxC.Utilitarios.Mensajes.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Problemas procesando la solicitud. Intentarlo más tarde..
        /// </summary>
        public static string MensajeGenerico {
            get {
                return ResourceManager.GetString("MensajeGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar algún mensaje acá.
        /// </summary>
        public static string MensajeNuevo {
            get {
                return ResourceManager.GetString("MensajeNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña ingresada posee caracteres inválidos..
        /// </summary>
        public static string ValidacionCaracteresContrasena {
            get {
                return ResourceManager.GetString("ValidacionCaracteresContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ingresado posee caracteres inválidos..
        /// </summary>
        public static string ValidacionCaracteresUsuario {
            get {
                return ResourceManager.GetString("ValidacionCaracteresUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos no pueden ser nulos..
        /// </summary>
        public static string ValidacionNulos {
            get {
                return ResourceManager.GetString("ValidacionNulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No posee permisos para utilizar este método. Revisar los datos suministrados Usuario y Contraseña..
        /// </summary>
        public static string ValidacionPermisosMetodo {
            get {
                return ResourceManager.GetString("ValidacionPermisosMetodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no posee permisos activos en la aplicación..
        /// </summary>
        public static string ValidacionPermisosUsuario {
            get {
                return ResourceManager.GetString("ValidacionPermisosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato de correo no es correcto, solamente direcciones de correo TEC..
        /// </summary>
        public static string CxC_EmailInvalido {
            get {
                return ResourceManager.GetString("CxC_EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de ejecución del servicio..
        /// </summary>
        public static string CxC_ErrordeEjecucion {
            get {
                return ResourceManager.GetString("CxC_ErrordeEjecucion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al generar el token de acceso..
        /// </summary>
        public static string CxC_ErrorGeneracionToken {
            get {
                return ResourceManager.GetString("CxC_ErrorGeneracionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LicenseId debe ser 1:basic; 2:Pro; 3:Corp..
        /// </summary>
        public static string CxC_LicenceIdInvalido {
            get {
                return ResourceManager.GetString("CxC_LicenceIdInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parámetros de entrada inválidos..
        /// </summary>
        public static string CxC_Parametros_invalidos {
            get {
                return ResourceManager.GetString("CxC_Parametros_invalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no debe ser mayor de 32 carácteres..
        /// </summary>
        public static string CxC_PasswordInvalido {
            get {
                return ResourceManager.GetString("CxC_PasswordInvalido", resourceCulture);
            }
        }
    }
}
