//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCCxCMaestro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCCxCMaestro()
        {
            this.FCCxCMaestro1 = new HashSet<FCCxCMaestro>();
            this.FCCxCMovimientoCuenta = new HashSet<FCCxCMovimientoCuenta>();
        }
    
        public int IdCuenta { get; set; }
        public int IdAuxiliar { get; set; }
        public int IdBoS { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public string TipMovimiento { get; set; }
        public Nullable<int> IdSocio { get; set; }
        public System.DateTime FecRegistro { get; set; }
        public System.DateTime FecInicioMorosidad { get; set; }
        public Nullable<System.DateTime> FecExpiracion { get; set; }
        public int IdEstado { get; set; }
        public string EstadoCobro { get; set; }
        public string IdLlaveExterna { get; set; }
        public string DscCargo { get; set; }
        public Nullable<int> IdCuentaAnterior { get; set; }
        public string UsrCreacion { get; set; }
        public string UsrUltModif { get; set; }
    
        public virtual FCCxCAuxiliar FCCxCAuxiliar { get; set; }
        public virtual FCCxCBienoServicio FCCxCBienoServicio { get; set; }
        public virtual FCCxCEstado FCCxCEstado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCMaestro> FCCxCMaestro1 { get; set; }
        public virtual FCCxCMaestro FCCxCMaestro2 { get; set; }
        public virtual FCCxCSocio FCCxCSocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCMovimientoCuenta> FCCxCMovimientoCuenta { get; set; }
    }
}
