//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCCxCActiEconomica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCCxCActiEconomica()
        {
            this.FCCXCDocumentoElectronico = new HashSet<FCCXCDocumentoElectronico>();
        }
    
        public int IdActiEconomica { get; set; }
        public Nullable<int> CodMdH { get; set; }
        public string DscActividad { get; set; }
        public Nullable<int> IndDevuelveIVA { get; set; }
        public Nullable<bool> IndActiPrincipal { get; set; }
        public Nullable<int> IdImporteIVA { get; set; }
        public Nullable<System.DateTime> FecCreacion { get; set; }
        public string UsrCreacion { get; set; }
        public Nullable<System.DateTime> FecUltModif { get; set; }
        public string UsrUltModif { get; set; }
    
        public virtual FCCxCImporteIVA FCCxCImporteIVA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCXCDocumentoElectronico> FCCXCDocumentoElectronico { get; set; }
    }
}
