//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCCXCDocumentoElectronico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCCXCDocumentoElectronico()
        {
            this.FCCXCDetalles = new HashSet<FCCXCDetalles>();
            this.FCCXCInfoAdicional = new HashSet<FCCXCInfoAdicional>();
            this.FCCXCOtrosCargos = new HashSet<FCCXCOtrosCargos>();
        }
    
        public int IdDocumentoElectronico { get; set; }
        public Nullable<int> IdActiEonomica { get; set; }
        public Nullable<int> IdTipoDocumento { get; set; }
        public string NumDocumento { get; set; }
        public Nullable<System.DateTime> FecVencimiento { get; set; }
        public Nullable<int> IdSocio { get; set; }
        public Nullable<int> IdFormaPago { get; set; }
        public Nullable<int> IdCondicionVenta { get; set; }
        public string eMailEnvio { get; set; }
        public Nullable<float> PorDescuento { get; set; }
        public Nullable<int> IdRazonExoneración { get; set; }
        public int IdMoneda { get; set; }
        public string DscDocumento { get; set; }
        public Nullable<int> IdReferencia { get; set; }
        public Nullable<int> IdTipoReferencia { get; set; }
        public string NumDocumentoReferencia { get; set; }
        public string DscRazonReferencia { get; set; }
        public Nullable<int> IndMdH { get; set; }
        public Nullable<int> IndEstadoConta { get; set; }
        public Nullable<int> NumPeriodosConta { get; set; }
        public Nullable<int> IndRazonExonera { get; set; }
        public Nullable<float> MontoSubTotal { get; set; }
        public Nullable<float> MontoDescuento { get; set; }
        public Nullable<float> MontoImpuesto { get; set; }
        public Nullable<float> MontoExonerado { get; set; }
        public Nullable<float> MontoOtrosCargos { get; set; }
        public string UsrCreacion { get; set; }
        public Nullable<System.DateTime> FecCreacion { get; set; }
    
        public virtual FCCxCActiEconomica FCCxCActiEconomica { get; set; }
        public virtual FCCXCCondicionVenta FCCXCCondicionVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCXCDetalles> FCCXCDetalles { get; set; }
        public virtual FCCxCFormaPago FCCxCFormaPago { get; set; }
        public virtual FCCxCMonedas FCCxCMonedas { get; set; }
        public virtual FCCXCRazonExoneracion FCCXCRazonExoneracion { get; set; }
        public virtual FCCXCReferencia FCCXCReferencia { get; set; }
        public virtual FCCxCSocio FCCxCSocio { get; set; }
        public virtual FCCXCTipoDocumento FCCXCTipoDocumento { get; set; }
        public virtual FCCXCTipoReferencia FCCXCTipoReferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCXCInfoAdicional> FCCXCInfoAdicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCXCOtrosCargos> FCCXCOtrosCargos { get; set; }
    }
}
