//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCCxCPeriodo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCCxCPeriodo()
        {
            this.FCCxCBoSPrecio = new HashSet<FCCxCBoSPrecio>();
        }
    
        public int IdPeriodo { get; set; }
        public int IdAuxiliar { get; set; }
        public string DscPeriodo { get; set; }
        public System.DateTime FecInicio { get; set; }
        public System.DateTime FecFinal { get; set; }
    
        public virtual FCCxCAuxiliar FCCxCAuxiliar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCBoSPrecio> FCCxCBoSPrecio { get; set; }
    }
}
