//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCCXCOtrosCargos
    {
        public int IdOtrosCargos { get; set; }
        public Nullable<int> IdDocumento { get; set; }
        public Nullable<int> IdTipoCargo { get; set; }
        public Nullable<float> PorOtrosCargos { get; set; }
        public Nullable<decimal> MonOtrosCargos { get; set; }
        public Nullable<bool> IndTercero { get; set; }
        public int IdTercero { get; set; }
    
        public virtual FCCXCDocumentoElectronico FCCXCDocumentoElectronico { get; set; }
        public virtual FCCXCTipoCargoTerceros FCCXCTipoCargoTerceros { get; set; }
        public virtual FCCXCTipoOtrosCargos FCCXCTipoOtrosCargos { get; set; }
    }
}
