//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCCxCAuxiliar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCCxCAuxiliar()
        {
            this.FCCxCBienoServicio = new HashSet<FCCxCBienoServicio>();
            this.FCCxCBitacoraSucesos = new HashSet<FCCxCBitacoraSucesos>();
            this.FCCxCMaestro = new HashSet<FCCxCMaestro>();
            this.FCCxCMovimientoCuenta = new HashSet<FCCxCMovimientoCuenta>();
            this.FCCxCPeriodo = new HashSet<FCCxCPeriodo>();
        }
    
        public int IdAuxiliar { get; set; }
        public string DscAuxiliar { get; set; }
        public string CodEstado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCBienoServicio> FCCxCBienoServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCBitacoraSucesos> FCCxCBitacoraSucesos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCMaestro> FCCxCMaestro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCMovimientoCuenta> FCCxCMovimientoCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCPeriodo> FCCxCPeriodo { get; set; }
    }
}
