//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CxC.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCCxCConcepto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCCxCConcepto()
        {
            this.FCCxCBienoServicio = new HashSet<FCCxCBienoServicio>();
        }
    
        public int IdConcepto { get; set; }
        public string DscTipo { get; set; }
        public string CodEstado { get; set; }
        public string CtaFinancieraDebito { get; set; }
        public string CtaFinancieraCredito { get; set; }
        public string UsarExpiracion { get; set; }
        public int NumDiasExpira { get; set; }
        public string EnviaNotificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FCCxCBienoServicio> FCCxCBienoServicio { get; set; }
    }
}
